# location of assembly .fw.gz file
assembly_gz: ./keep/by_id/su92l-4zz18-lj22pmb8h3ty0w8/assembly.00.hg19.fw.gz

# location of assembly .fw.fwi file
assembly_fwi: ./keep/by_id/su92l-4zz18-lj22pmb8h3ty0w8/assembly.00.hg19.fw.fwi

# location of keep collection with sglf.gz files
sglf: ./keep/by_id/0005f6e64c510865d4997467764f305e+58830

# location of tile info array
# for complete tile set
tile_info: ./keep/by_id/1f769486fd7bbbba9dc3f06c411f5804+53847/outdir/all-info

# only for high quality tile set from PGP
#tile_info: ./keep/by_id/su92l-4zz18-xmmmg0qn0wuaxkl/hiq-pip-info

# location of gzipped reference vcf file. Needed for getRsids.py
ref_vcf: ./keep/by_id/su92l-4zz18-v96bt8gwbsini81/GRCh37p13.vcf.gz

features:
  # requires sglf
  - diff_indices

  # requires assembly_fwi 
  - location

  # requires assembly_gz
  - base_pair_locations

  # requires sglf
  - variant_diffs
